// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pg_pb3.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WireMessageType int32

const (
	WireMessageType_WMSG_BEGIN  WireMessageType = 0
	WireMessageType_WMSG_COMMIT WireMessageType = 1
	WireMessageType_WMSG_INSERT WireMessageType = 2
	WireMessageType_WMSG_UPDATE WireMessageType = 3
	WireMessageType_WMSG_DELETE WireMessageType = 4
)

// Enum value maps for WireMessageType.
var (
	WireMessageType_name = map[int32]string{
		0: "WMSG_BEGIN",
		1: "WMSG_COMMIT",
		2: "WMSG_INSERT",
		3: "WMSG_UPDATE",
		4: "WMSG_DELETE",
	}
	WireMessageType_value = map[string]int32{
		"WMSG_BEGIN":  0,
		"WMSG_COMMIT": 1,
		"WMSG_INSERT": 2,
		"WMSG_UPDATE": 3,
		"WMSG_DELETE": 4,
	}
)

func (x WireMessageType) Enum() *WireMessageType {
	p := new(WireMessageType)
	*p = x
	return p
}

func (x WireMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WireMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pg_pb3_proto_enumTypes[0].Descriptor()
}

func (WireMessageType) Type() protoreflect.EnumType {
	return &file_pg_pb3_proto_enumTypes[0]
}

func (x WireMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WireMessageType.Descriptor instead.
func (WireMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{0}
}

type WireMessageHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typ WireMessageType `protobuf:"varint,1,opt,name=typ,proto3,enum=main.WireMessageType" json:"typ,omitempty"`
}

func (x *WireMessageHeader) Reset() {
	*x = WireMessageHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireMessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireMessageHeader) ProtoMessage() {}

func (x *WireMessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireMessageHeader.ProtoReflect.Descriptor instead.
func (*WireMessageHeader) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{0}
}

func (x *WireMessageHeader) GetTyp() WireMessageType {
	if x != nil {
		return x.Typ
	}
	return WireMessageType_WMSG_BEGIN
}

type BeginTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeginTransaction) Reset() {
	*x = BeginTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransaction) ProtoMessage() {}

func (x *BeginTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransaction.ProtoReflect.Descriptor instead.
func (*BeginTransaction) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{1}
}

type CommitTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitTransaction) Reset() {
	*x = CommitTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransaction) ProtoMessage() {}

func (x *CommitTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransaction.ProtoReflect.Descriptor instead.
func (*CommitTransaction) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{2}
}

type InsertDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table     *TableDescription    `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	NewValues *FieldSetDescription `protobuf:"bytes,3,opt,name=new_values,json=newValues,proto3" json:"new_values,omitempty"`
}

func (x *InsertDescription) Reset() {
	*x = InsertDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDescription) ProtoMessage() {}

func (x *InsertDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDescription.ProtoReflect.Descriptor instead.
func (*InsertDescription) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{3}
}

func (x *InsertDescription) GetTable() *TableDescription {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *InsertDescription) GetNewValues() *FieldSetDescription {
	if x != nil {
		return x.NewValues
	}
	return nil
}

type UpdateDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table     *TableDescription    `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	KeyFields *FieldSetDescription `protobuf:"bytes,3,opt,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	NewValues *FieldSetDescription `protobuf:"bytes,5,opt,name=new_values,json=newValues,proto3" json:"new_values,omitempty"`
}

func (x *UpdateDescription) Reset() {
	*x = UpdateDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDescription) ProtoMessage() {}

func (x *UpdateDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDescription.ProtoReflect.Descriptor instead.
func (*UpdateDescription) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDescription) GetTable() *TableDescription {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *UpdateDescription) GetKeyFields() *FieldSetDescription {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

func (x *UpdateDescription) GetNewValues() *FieldSetDescription {
	if x != nil {
		return x.NewValues
	}
	return nil
}

type DeleteDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table     *TableDescription    `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	KeyFields *FieldSetDescription `protobuf:"bytes,3,opt,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
}

func (x *DeleteDescription) Reset() {
	*x = DeleteDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDescription) ProtoMessage() {}

func (x *DeleteDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDescription.ProtoReflect.Descriptor instead.
func (*DeleteDescription) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDescription) GetTable() *TableDescription {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *DeleteDescription) GetKeyFields() *FieldSetDescription {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

type TableDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaName string `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName  string `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	TableOid   uint32 `protobuf:"varint,3,opt,name=table_oid,json=tableOid,proto3" json:"table_oid,omitempty"`
}

func (x *TableDescription) Reset() {
	*x = TableDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableDescription) ProtoMessage() {}

func (x *TableDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableDescription.ProtoReflect.Descriptor instead.
func (*TableDescription) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{6}
}

func (x *TableDescription) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *TableDescription) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableDescription) GetTableOid() uint32 {
	if x != nil {
		return x.TableOid
	}
	return 0
}

type FieldSetDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names    []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Values   [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	TypeOids []uint32 `protobuf:"varint,4,rep,packed,name=type_oids,json=typeOids,proto3" json:"type_oids,omitempty"`
	Nulls    []byte   `protobuf:"bytes,5,opt,name=nulls,proto3" json:"nulls,omitempty"`
	Formats  []byte   `protobuf:"bytes,6,opt,name=formats,proto3" json:"formats,omitempty"`
}

func (x *FieldSetDescription) Reset() {
	*x = FieldSetDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pg_pb3_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldSetDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSetDescription) ProtoMessage() {}

func (x *FieldSetDescription) ProtoReflect() protoreflect.Message {
	mi := &file_pg_pb3_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSetDescription.ProtoReflect.Descriptor instead.
func (*FieldSetDescription) Descriptor() ([]byte, []int) {
	return file_pg_pb3_proto_rawDescGZIP(), []int{7}
}

func (x *FieldSetDescription) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *FieldSetDescription) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FieldSetDescription) GetTypeOids() []uint32 {
	if x != nil {
		return x.TypeOids
	}
	return nil
}

func (x *FieldSetDescription) GetNulls() []byte {
	if x != nil {
		return x.Nulls
	}
	return nil
}

func (x *FieldSetDescription) GetFormats() []byte {
	if x != nil {
		return x.Formats
	}
	return nil
}

var File_pg_pb3_proto protoreflect.FileDescriptor

var file_pg_pb3_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x67, 0x5f, 0x70, 0x62, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x3c, 0x0a, 0x11, 0x57, 0x69, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x74, 0x79, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x74,
	0x79, 0x70, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x11, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x38,
	0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6e,
	0x65, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c,
	0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0a,
	0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x65, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6b, 0x65, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x7b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x53, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x6f, 0x0a,
	0x10, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x69, 0x64, 0x22, 0x90,
	0x01, 0x0a, 0x13, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6f, 0x69, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4f, 0x69, 0x64,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x75, 0x6c, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6e, 0x75, 0x6c, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x73, 0x2a, 0x65, 0x0a, 0x0f, 0x57, 0x69, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x4d, 0x53, 0x47, 0x5f, 0x42, 0x45, 0x47,
	0x49, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x4d, 0x53, 0x47, 0x5f, 0x49, 0x4e,
	0x53, 0x45, 0x52, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x4d, 0x53, 0x47, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x4d, 0x53, 0x47, 0x5f,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pg_pb3_proto_rawDescOnce sync.Once
	file_pg_pb3_proto_rawDescData = file_pg_pb3_proto_rawDesc
)

func file_pg_pb3_proto_rawDescGZIP() []byte {
	file_pg_pb3_proto_rawDescOnce.Do(func() {
		file_pg_pb3_proto_rawDescData = protoimpl.X.CompressGZIP(file_pg_pb3_proto_rawDescData)
	})
	return file_pg_pb3_proto_rawDescData
}

var file_pg_pb3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pg_pb3_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pg_pb3_proto_goTypes = []interface{}{
	(WireMessageType)(0),        // 0: main.WireMessageType
	(*WireMessageHeader)(nil),   // 1: main.WireMessageHeader
	(*BeginTransaction)(nil),    // 2: main.BeginTransaction
	(*CommitTransaction)(nil),   // 3: main.CommitTransaction
	(*InsertDescription)(nil),   // 4: main.InsertDescription
	(*UpdateDescription)(nil),   // 5: main.UpdateDescription
	(*DeleteDescription)(nil),   // 6: main.DeleteDescription
	(*TableDescription)(nil),    // 7: main.TableDescription
	(*FieldSetDescription)(nil), // 8: main.FieldSetDescription
}
var file_pg_pb3_proto_depIdxs = []int32{
	0, // 0: main.WireMessageHeader.typ:type_name -> main.WireMessageType
	7, // 1: main.InsertDescription.table:type_name -> main.TableDescription
	8, // 2: main.InsertDescription.new_values:type_name -> main.FieldSetDescription
	7, // 3: main.UpdateDescription.table:type_name -> main.TableDescription
	8, // 4: main.UpdateDescription.key_fields:type_name -> main.FieldSetDescription
	8, // 5: main.UpdateDescription.new_values:type_name -> main.FieldSetDescription
	7, // 6: main.DeleteDescription.table:type_name -> main.TableDescription
	8, // 7: main.DeleteDescription.key_fields:type_name -> main.FieldSetDescription
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pg_pb3_proto_init() }
func file_pg_pb3_proto_init() {
	if File_pg_pb3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pg_pb3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WireMessageHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pg_pb3_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldSetDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pg_pb3_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pg_pb3_proto_goTypes,
		DependencyIndexes: file_pg_pb3_proto_depIdxs,
		EnumInfos:         file_pg_pb3_proto_enumTypes,
		MessageInfos:      file_pg_pb3_proto_msgTypes,
	}.Build()
	File_pg_pb3_proto = out.File
	file_pg_pb3_proto_rawDesc = nil
	file_pg_pb3_proto_goTypes = nil
	file_pg_pb3_proto_depIdxs = nil
}
